run:
  timeout: 5m
  go: "1.22"
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - bodyclose
    - misspell

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104
  revive:
    rules:
      - name: exported
        arguments: [checkPrivateReceivers]
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
